CREATE TABLE TICKET(
  ID          BINARY NOT NULL,
  DESCRIPTION VARCHAR(255),
  EMAIL       VARCHAR(255),
  NUMBER      VARCHAR(255) NOT NULL,
  PRIORITY    VARCHAR(255),
  TITLE       VARCHAR(255),
  STATUS VARCHAR(255),
  CREATED TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE (NUMBER)
);
