CREATE TABLE TICKET(
  ID          BINARY NOT NULL,
  DESCRIPTION VARCHAR(255),
  EMAIL       VARCHAR(255),
  NUMBER      VARCHAR(255) NOT NULL,
  PRIORITY    INT,
  TITLE       VARCHAR(255),
  STATUS      INT,
  CREATED TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE (NUMBER)
);
